export const patients = [
  {
    id: 1,
    first_name: "Corrinne",
    last_name: "Rawls",
    phone: "439-640-7897",
    email: "crawls0@instagram.com",
    birthYear: 1961,
    isSick: false,
  },
  {
    id: 2,
    first_name: "Josepha",
    last_name: "Kittman",
    phone: "788-333-5444",
    email: "jkittman1@storify.com",
    birthYear: 2015,
    isSick: false,
  },
  {
    id: 3,
    first_name: "Kym",
    last_name: "Giametti",
    phone: "983-973-6156",
    email: "kgiametti2@ca.gov",
    birthYear: 1970,
    isSick: false,
  },
  {
    id: 4,
    first_name: "Lisbeth",
    last_name: "Brammer",
    phone: "775-720-7343",
    email: "lbrammer3@w3.org",
    birthYear: 1998,
    isSick: false,
  },
  {
    id: 5,
    first_name: "Osgood",
    last_name: "Dibley",
    phone: "964-446-8556",
    email: "odibley4@clickbank.net",
    birthYear: 2008,
    isSick: false,
  },
  {
    id: 6,
    first_name: "Clifford",
    last_name: "Dugdale",
    phone: "217-928-2480",
    email: "cdugdale5@archive.org",
    birthYear: 1993,
    isSick: false,
  },
  {
    id: 7,
    first_name: "Samuele",
    last_name: "Pattrick",
    phone: "794-213-5186",
    email: "spattrick6@moonfruit.com",
    birthYear: 1987,
    isSick: false,
  },
  {
    id: 8,
    first_name: "Filia",
    last_name: "Presdee",
    phone: "790-551-7616",
    email: "fpresdee7@pagesperso-orange.fr",
    birthYear: 1962,
    isSick: false,
  },
  {
    id: 9,
    first_name: "Mavra",
    last_name: "Dorran",
    phone: "250-540-3709",
    email: "mdorran8@lulu.com",
    birthYear: 1960,
    isSick: false,
  },
  {
    id: 10,
    first_name: "Mortie",
    last_name: "Gisby",
    phone: "819-535-0244",
    email: "mgisby9@ebay.co.uk",
    birthYear: 1948,
    isSick: false,
  },
  {
    id: 11,
    first_name: "Alexis",
    last_name: "Lockless",
    phone: "749-849-9551",
    email: "alocklessa@home.pl",
    birthYear: 2010,
    isSick: false,
  },
  {
    id: 12,
    first_name: "Cosimo",
    last_name: "Johanchon",
    phone: "709-449-9706",
    email: "cjohanchonb@latimes.com",
    birthYear: 1996,
    isSick: false,
  },
  {
    id: 13,
    first_name: "Elwyn",
    last_name: "Riden",
    phone: "248-974-0827",
    email: "eridenc@cam.ac.uk",
    birthYear: 1960,
    isSick: false,
  },
  {
    id: 14,
    first_name: "Thorn",
    last_name: "Tomson",
    phone: "181-966-6472",
    email: "ttomsond@eepurl.com",
    birthYear: 1980,
    isSick: false,
  },
  {
    id: 15,
    first_name: "Codee",
    last_name: "Beglin",
    phone: "501-863-9221",
    email: "cbegline@yellowpages.com",
    birthYear: 1983,
    isSick: false,
  },
  {
    id: 16,
    first_name: "Witty",
    last_name: "Tabner",
    phone: "956-945-2896",
    email: "wtabnerf@nifty.com",
    birthYear: 1959,
    isSick: false,
  },
  {
    id: 17,
    first_name: "Emalia",
    last_name: "Coull",
    phone: "758-880-8621",
    email: "ecoullg@blogger.com",
    birthYear: 2011,
    isSick: false,
  },
  {
    id: 18,
    first_name: "Harrie",
    last_name: "Zanuciolii",
    phone: "229-850-8600",
    email: "hzanucioliih@mail.ru",
    birthYear: 1997,
    isSick: false,
  },
  {
    id: 19,
    first_name: "Maegan",
    last_name: "Lidyard",
    phone: "841-898-8411",
    email: "mlidyardi@spiegel.de",
    birthYear: 1989,
    isSick: false,
  },
  {
    id: 20,
    first_name: "Claude",
    last_name: "Zwicker",
    phone: "972-506-7886",
    email: "czwickerj@mail.ru",
    birthYear: 1998,
    isSick: false,
  },
  {
    id: 21,
    first_name: "Flor",
    last_name: "Crayton",
    phone: "927-159-0843",
    email: "fcraytonk@hhs.gov",
    birthYear: 2013,
    isSick: false,
  },
  {
    id: 22,
    first_name: "Erich",
    last_name: "Tocque",
    phone: "182-179-9127",
    email: "etocquel@sphinn.com",
    birthYear: 1953,
    isSick: false,
  },
  {
    id: 23,
    first_name: "Bibi",
    last_name: "Chiechio",
    phone: "592-905-8179",
    email: "bchiechiom@disqus.com",
    birthYear: 2015,
    isSick: false,
  },
  {
    id: 24,
    first_name: "Prisca",
    last_name: "Headech",
    phone: "308-369-0147",
    email: "pheadechn@purevolume.com",
    birthYear: 1981,
    isSick: false,
  },
  {
    id: 25,
    first_name: "Calley",
    last_name: "Feldbaum",
    phone: "106-869-0973",
    email: "cfeldbaumo@oaic.gov.au",
    birthYear: 1966,
    isSick: false,
  },
  {
    id: 26,
    first_name: "Bryon",
    last_name: "Keneford",
    phone: "892-110-3696",
    email: "bkenefordp@newsvine.com",
    birthYear: 1999,
    isSick: false,
  },
  {
    id: 27,
    first_name: "Matilde",
    last_name: "Breinlein",
    phone: "429-528-1152",
    email: "mbreinleinq@woothemes.com",
    birthYear: 1991,
    isSick: false,
  },
  {
    id: 28,
    first_name: "Edita",
    last_name: "Lowy",
    phone: "911-902-5263",
    email: "elowyr@imgur.com",
    birthYear: 2014,
    isSick: false,
  },
  {
    id: 29,
    first_name: "Sergeant",
    last_name: "Harken",
    phone: "152-927-6977",
    email: "sharkens@cnbc.com",
    birthYear: 1994,
    isSick: false,
  },
  {
    id: 30,
    first_name: "Babbie",
    last_name: "Aubery",
    phone: "346-880-7298",
    email: "bauberyt@vk.com",
    birthYear: 1984,
    isSick: false,
  },
  {
    id: 31,
    first_name: "Zelma",
    last_name: "Verbruggen",
    phone: "509-217-4197",
    email: "zverbruggenu@netlog.com",
    birthYear: 1991,
    isSick: false,
  },
  {
    id: 32,
    first_name: "Janetta",
    last_name: "Snipe",
    phone: "730-272-4636",
    email: "jsnipev@weebly.com",
    birthYear: 1977,
    isSick: false,
  },
  {
    id: 33,
    first_name: "Raynard",
    last_name: "Ehlerding",
    phone: "344-589-9321",
    email: "rehlerdingw@google.ru",
    birthYear: 1971,
    isSick: false,
  },
  {
    id: 34,
    first_name: "Addy",
    last_name: "Klee",
    phone: "960-225-4336",
    email: "akleex@360.cn",
    birthYear: 1977,
    isSick: false,
  },
  {
    id: 35,
    first_name: "Bucky",
    last_name: "Camell",
    phone: "529-113-1080",
    email: "bcamelly@imgur.com",
    birthYear: 1969,
    isSick: false,
  },
  {
    id: 36,
    first_name: "Bren",
    last_name: "Janko",
    phone: "975-904-1166",
    email: "bjankoz@usda.gov",
    birthYear: 1991,
    isSick: false,
  },
  {
    id: 37,
    first_name: "Joshia",
    last_name: "Rowlands",
    phone: "818-524-7591",
    email: "jrowlands10@unblog.fr",
    birthYear: 1961,
    isSick: false,
  },
  {
    id: 38,
    first_name: "Gaston",
    last_name: "Berndsen",
    phone: "994-323-3689",
    email: "gberndsen11@1und1.de",
    birthYear: 1982,
    isSick: false,
  },
  {
    id: 39,
    first_name: "Nollie",
    last_name: "O'Heffernan",
    phone: "410-373-5614",
    email: "noheffernan12@moonfruit.com",
    birthYear: 2012,
    isSick: false,
  },
  {
    id: 40,
    first_name: "Grover",
    last_name: "Cumming",
    phone: "911-160-2225",
    email: "gcumming13@jigsy.com",
    birthYear: 2000,
    isSick: false,
  },
  {
    id: 41,
    first_name: "Clerissa",
    last_name: "Riceards",
    phone: "843-630-5621",
    email: "criceards14@thetimes.co.uk",
    birthYear: 1991,
  },
  {
    id: 42,
    first_name: "Sarine",
    last_name: "Ryson",
    phone: "134-760-7794",
    email: "sryson15@simplemachines.org",
    birthYear: 1979,
    isSick: false,
  },
  {
    id: 43,
    first_name: "Lurette",
    last_name: "Audenis",
    phone: "621-501-1684",
    email: "laudenis16@home.pl",
    birthYear: 1970,
    isSick: false,
  },
  {
    id: 44,
    first_name: "Innis",
    last_name: "Sherlock",
    phone: "556-436-2108",
    email: "isherlock17@gizmodo.com",
    birthYear: 1999,
    isSick: false,
  },
  {
    id: 45,
    first_name: "Alexandr",
    last_name: "Yakolev",
    phone: "619-501-9847",
    email: "ayakolev18@nba.com",
    birthYear: 1970,
    isSick: false,
  },
  {
    id: 46,
    first_name: "Mill",
    last_name: "Boots",
    phone: "151-385-3410",
    email: "mboots19@clickbank.net",
    birthYear: 1996,
    isSick: false,
  },
  {
    id: 47,
    first_name: "Willi",
    last_name: "Devil",
    phone: "225-899-2236",
    email: "wdevil1a@ucoz.ru",
    birthYear: 1997,
    isSick: false,
  },
  {
    id: 48,
    first_name: "Marina",
    last_name: "Sivorn",
    phone: "414-976-1256",
    email: "msivorn1b@cyberchimps.com",
    birthYear: 1971,
    isSick: false,
  },
  {
    id: 49,
    first_name: "Wallache",
    last_name: "Standell",
    phone: "879-961-7013",
    email: "wstandell1c@tiny.cc",
    birthYear: 1945,
    isSick: false,
  },
  {
    id: 50,
    first_name: "Shane",
    last_name: "Jikovsky",
    phone: "206-613-4159",
    email: "sjikovsky1d@flickr.com",
    birthYear: 2016,
    isSick: false,
  },
];

export const dentists = [
  {
    id: 1,
    first_name: "Teun de",
    last_name: "Wit",
    phone: "06-76812443",
    email: "teun.de.wit@tandartspraktijkbvt.nl",
    role: "dentist",
    isSick: false,
  },
  {
    id: 2,
    first_name: "Reinout van der",
    last_name: "Veen",
    phone: "06-53387678",
    email: "reinout.van.der.veen@tandartspraktijkbvt.nl",
    role: "dentist",
    isSick: false,
  },
  {
    id: 3,
    first_name: "Mirthe",
    last_name: "Meijer",
    phone: "06-90117690",
    email: "mirthe.meijer@tandartspraktijkbvt.nl",
    role: "dentist",
    isSick: false,
  },
  {
    id: 4,
    first_name: "Lisa",
    last_name: "Kok",
    phone: "06-90021442",
    email: "lisa.kok@tandartspraktijkbvt.nl",
    role: "dentist",
    isSick: true,
  },
];

export const assistants = [
  {
    id: 1,
    first_name: "Thea",
    last_name: "Kramer",
    phone: "06-48334012",
    email: "thea.kramer@tandartspraktijkbvt.nl",
    role: "assistant",
    isSick: false,
  },
  {
    id: 2,
    first_name: "Lotte",
    last_name: "Vos",
    phone: "06-04487922",
    email: "lotte.vos@tandartspraktijkbvt.nl",
    role: "assistant",
    isSick: false,
  },
];

